### ISSUE TITLE
Rewrite in Java?

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/stata-parquet#12]
It appears that the Java API (at least for Stata 15) is considerably nicer. I just tested it and it appears that Stata will automatically widen string columns when trying to enter wider strings, which would be very helpful.

It's definitely worth discussing this before you spend too much time on C++ code. I could try to code up a prototype in Java this weekend.

- High level overview: https://www.stata.com/new-in-stata/java-plugins/
- Stata Java API: https://www.stata.com/java/api15/

Here's "hello world" code to reproduce:
```java
import com.stata.sfi.*;
public class HelloFromJava
{
        public static int sayhello(String[] args)
        {
               SFIToolkit.displayln("Hello from java!") ;
               int var_num = Data.addVarStr("str_var", 2);
               SFIToolkit.displayln("Created str var of length 1") ;
               long obs_num = 1;
               Data.storeStr(1, obs_num, "a");
               long obs_num2 = 2;
               Data.storeStr(1, obs_num2, "abcd");
               SFIToolkit.displayln(Macro.getGlobal("S_MACH")) ;
               return(0) ;      // Stata return code
        }
}
```

Compile with (on mac at least):
```bash
javac -classpath sfi-api.jar HelloFromJava.java
jar cvf tryjava.jar HelloFromJava.class
cp tryjava.jar ~/Library/Application\ Support/Stata/ado/personal/t/tryjava.jar
```

Stata program:
```stata
program tryjava
       version 15
       clear
       set obs 2
       javacall HelloFromJava sayhello, jar(tryjava.jar)
end
```

This gives:
![image](https://user-images.githubusercontent.com/15164633/47834528-3501f400-dd76-11e8-8af5-d1177ed69e86.png)

**Comment by mcaceresb** [comment]
Interesting. Haven't tried read/write for the Arrow Java library. I doubt there will be too much difference in terms of speed, so def worth looking into. I haven't used Java, tho. Is it on the server?

**Comment by kylebarron** [comment]
I vaguely looked at it once before, but stopped because of general bias against Java. 

Stata ships with the Java 8 runtime environment. On the server the path is:
```
/disk/admin/Linux-local/stata14/utilities/java/linux-x64/jre1.8.0_121/bin/java
/disk/admin/Linux-local/stata15/utilities/java/linux-x64/jre1.8.0_162/bin/java
```

I'm too knowledgeable about the Java world, but I think it might be easier to distribute a `.jar` file that users don't have to compile themselves.

**Comment by kylebarron** [comment]
@mcaceresb 	
Should I try out a prototype on a different branch or should I start a different repo?

**Comment by kylebarron** [comment]
I'll plan to read through this as a quick tutorial:
https://learnxinyminutes.com/docs/java/

**Comment by mcaceresb** [comment]
> I'm too knowledgeable about the Java world

Brag much? x)

> Should I try out a prototype on a different branch or should I start a different repo?

As you wish. I'm happy to explore Java on a diff branch. If it works then it would supersede the C++ API bc I think it will be easier to support missing values and strings, so import/export would for sure be lossless. (Although if most CMS strings have fixed width, the current C++ plugin should work OK; the only thing that would be concerning are missing values in integers when exporting.)

In any case, I don't really see a reason to keep both unless Java is much slower, but I doubt that will be the case; for large data any overhead will be small relative to read and write times.

**Comment by kylebarron** [comment]
Hahahaha. I think it was clear I meant to say "not too".

I posted a project structure here: https://github.com/kylebarron/stataParquet, but I can move it onto a branch here if you want. I just didn't want to carry the C++ history in the Java code. It was surprisingly easy to pull in the Parquet dependencies. I just put the dependencies in `pom.xml` and run `mvn package`.

> Although if most CMS strings have fixed width, the current C++ plugin should work OK

But Spark can't read fixed width strings. And especially if we're developing this in the context of interoperability with Spark with Medicare data, this is very important.

> any overhead will be small relative to read and write times

I've heard there's some overhead when starting the JVM but for a large file that should be negligible.

**Comment by mcaceresb** [comment]
> But Spark can't read fixed width strings. 

They get read as ByteArray by default. The code scans the first 2^16 rows for string length, so if the width is fixed that should give back the correct width, is what I meant.

> I posted a project structure here

Cool. Let me know if/when you get it up and running or if any issues pop up.

**Comment by kylebarron** [comment]
I'll try to at least have a very minimal example, i.e. maybe just integer type, working tonight.

**Comment by kylebarron** [comment]
Have you worked with Java before? I'm having trouble getting Stata to see the class within the Jar. I keep getting:
![image](https://user-images.githubusercontent.com/15164633/47885196-2e24c100-de0a-11e8-8f66-c17fd1d20ed9.png)

**Comment by mcaceresb** [comment]
Is that how you call the plugin? Isn't it just "HelloFromJava" instead of the full thing?I have to say, though, I haven't work with java at all (as in, I don't think I've ever even typed `jar` into the CLI once; I guess that's about to change!)

**Comment by kylebarron** [comment]
Right now it's only working in Stata when I start Stata in the directory of the `.jar` file

**Comment by kylebarron** [comment]
I have a lot to explain and it'll take a while to type

**Comment by kylebarron** [comment]
The difference between now and last night is that I'm trying to use the Java build system Maven...

The "correct" name does work when the `jar` is in my current directory
![image](https://user-images.githubusercontent.com/15164633/47885955-df792600-de0d-11e8-8a07-1e92804901e6.png)

**Comment by mcaceresb** [comment]
In my experience this library lookup thing is solved by setting `LD_LIBRARY_PATH`; not sure if java works the same way.

**Comment by kylebarron** [comment]
I think I discovered the issue...

Stata tells you to put the `.jar` in your `PERSONAL` directory, but then apparently on Linux doesn't search recursively for it. So if you put your `.jar` at `$PERSONAL/t/tryjava.jar`, it won't work. 

On mac, it does search recursively.

**Comment by kylebarron** [comment]
So when I'm not in the `PERSONAL` directory, one works while the other doesn't.
![image](https://user-images.githubusercontent.com/15164633/47886129-bd33d800-de0e-11e8-9770-40352273c010.png)
![image](https://user-images.githubusercontent.com/15164633/47886137-c45ae600-de0e-11e8-805f-0e5d7a9d0625.png)

**Comment by kylebarron** [comment]
Once I move `stataParquet.jar` to the top level of `PERSONAL`, it works:
![image](https://user-images.githubusercontent.com/15164633/47886175-f9673880-de0e-11e8-9948-952a308b7ea4.png)

**Comment by kylebarron** [comment]
That's definitely a Stata bug. Worth it to email them?

**Comment by mcaceresb** [comment]
Sure, but I doubt that it will make it into an update any time soon (they do update, but it's every few months I think, not every other week).

**Comment by kylebarron** [comment]
And still, since updates are optional you can't assume any user has it

**Comment by kylebarron** [comment]
In any case, my repo has a hello-world java example to print to Stata. It seems that in the Java world, the choices of what structure to load the Parquet file into are more fractured.

These repos seem like good starting points:
- https://github.com/tideworks/parquet2csv
- https://github.com/tideworks/arvo2parquet

- Reddit post: https://www.reddit.com/r/java/comments/8kp5av/writing_parquet_format_data_to_regular_files_ie/

- Another reader/writer to avro: https://github.com/MaxNevermind/Hadoop-snippets/blob/master/src/main/java/org/maxkons/hadoop_snippets/parquet/ParquetReaderWriterWithAvro.java

- from `parquet-cli`: https://github.com/apache/parquet-mr/blob/master/parquet-cli/src/main/java/org/apache/parquet/cli/Main.java

- gist that looks really easy but that I passed over the first time because it didn't have a `pom.xml`: https://gist.github.com/animeshtrivedi/76de64f9dab1453958e1d4f8eca1605f

**Comment by kylebarron** [comment]
I put the [fourth one](https://github.com/MaxNevermind/Hadoop-snippets/blob/master/src/main/java/org/maxkons/hadoop_snippets/parquet/ParquetReaderWriterWithAvro.java) on my [dev branch](https://github.com/kylebarron/stataParquet/tree/dev) and updated my `pom.xml`... I got it to at least fix all the linter errors, but haven't run it yet.

If you clone it and then do
```
mvn dependency:resolve
```
it should download all the dependencies for you automatically.

**Comment by mcaceresb** [comment]
I mean, I don't even know what to type into the CLI to...compile? A java file? I mean, google's top results tell me the script but not how to run it. So:

1. Hello world in Java.
2. Parquet reader and writer in Java.
3. ???
4. Profit

**Comment by mcaceresb** [comment]
I don't even understand the naming convention? Why the 17 nested folders? I assume there's a reason; I've seen it in a few places now.

**Comment by kylebarron** [comment]
Make sure that Java is at least version 8 (`java -version` should show `1.8`).

The first post of this issue gives the most basic commands to compile the Java code and link it to Stata.

When you compile Java code, instead of it compiling to assembly code, like C/C++, it compiles to bytecode that then runs on the Java Virtual Machine (JVM). While I don't think this bytecode is necessarily quite as fast as raw assembly code, this has the advantage of being able to run without modification on any platform that the JVM supports. So the great thing about this code is that you can do 
```
javac -classpath sfi-api.jar HelloFromJava.java
```
and then the `HelloFromJava.class` file that's created can run on Windows, Mac, or Linux without modification or further compilation.

It's annoying to distribute tons of individual class files, so the next step is to zip them together into a single file, the `.jar` file. I think this is literally a `.zip` file with a renamed suffix. This is the file that Stata runs.

The difference between a Java project and a "Java library" meant to be a plugin for Stata is that the latter doesn't have a `main` method. See these two Stata links:

- https://www.stata.com/help.cgi?java
- https://www.stata.com/help.cgi?javacall

as well as the Java API and Stata 15 Java overview:

- https://www.stata.com/java/api15/
- https://www.stata.com/new-in-stata/java-plugins/

## Dependency Management

You should install [Maven](https://maven.apache.org/), the dependency manager, and then read the [5 minute intro](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html). 

All Maven projects have [the same directory structure](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). I think this is kinda annoying because there are so many empty folders, but it's just how Java projects are I think. (It might be Maven specifically that enforces this structure; another Java dependency manager is called "Gradle", and I don't really know anything about it but I don't think it enforces the same directory structure).

## Hello world with Maven

So the full reproduction for the hello world currently on the master branch here https://github.com/kylebarron/stataParquet/commit/d7ff8c224ef9d46bc287288926ed6ece0e74f39f is:

```
git clone https://github.com/kylebarron/stataParquet
git checkout d7ff8c224ef9d46bc287288926ed6ece0e74f39f
mvn package
```
The `mvn package` command builds the entire project according to the structure noted in `pom.xml`. The finished `.jar` is in the `target/` folder. Then move that `.jar` to your `PERSONAL` folder (but not a nested folder), and run:
```
javacall ParquetReader sayhello, jar(name_of_jar.jar)
```
since `ParquetReader` is the name of the class and `sayhello` is the name of the function.

**Comment by mcaceresb** [comment]
Oh god, I tried to run their example and get a build success message, but right before I saw

```
[WARNING] JAR will be empty - no content was marked for inclusion!
```

I looked it up and everyone who asked gets a response of "you better be using the default directory structure." I'm sure it's great for projects, but not very helpful when I just want to debug a hello, world...

**Comment by kylebarron** [comment]
Which example? the Stata hello world example?

**Comment by mcaceresb** [comment]
No, the one on Maven's website. I really don't think it's worthwhile to try to get Stata to run if I haven't even printed "Hello, world!" from Java.

**Comment by mcaceresb** [comment]
(From Java directly, I mean.)

**Comment by kylebarron** [comment]
There's a simpler Hello world... File named `HelloWorld.java`
```java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World");
    }
}
```
Then 
```
javac HelloWorld.java
```
creates `HelloWorld.class`. To run that, just run `java HelloWorld`:
```
kyle at mac in ~                                                         × 0:06
> java HelloWorld
Hello, World
```

**Comment by mcaceresb** [comment]
But I'm trying to get the Hello World via maven!

**Comment by kylebarron** [comment]
Oh sorry

**Comment by mcaceresb** [comment]
I think I figured out what I did wrong. I already had an existing pom file and stuff when I started. I think I should have started from an empty dir.

**Comment by kylebarron** [comment]
Yeah, the `maven archetype` helps a lot

**Comment by mcaceresb** [comment]
Right, that failed, but I think bc the dir was non-empty.

**Comment by kylebarron** [comment]
This creates a java project structure for you:
```
mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
```

**Comment by kylebarron** [comment]
I see. It worked on the first try for me

**Comment by kylebarron** [comment]
Tbh doing Hello World in Stata was simpler to get started with than Maven

**Comment by mcaceresb** [comment]
Yes, it just worked for me as well. I just had to start with an empty dir it seems. Anyway, onward!

**Comment by mcaceresb** [comment]
I can't get a java that includes any arrow imports (`import org.apache.arrow.vector.class`) to run if I use anything that is imported. Ah, well. I'm giving up for now. Might try again in the weekend; let me know if you do get arrow to run. I think it makes more sense to get an arrow example as a standalone first, but whichever you can manage is good.

**Comment by mcaceresb** [comment]
I can't get a java that includes any arrow imports (`import org.apache.arrow.vector.class`) to run if I use anything that is imported. Ah, well. I'm giving up for now. Might try again in the weekend; let me know if you do get arrow to run. I think it makes more sense to get an arrow example as a standalone first, but whichever you can manage is good.

**Comment by kylebarron** [comment]
Did you update `pom.xml` with the new dependency?

**Comment by kylebarron** [comment]
And then run `mvn dependency:resolve`? I think

**Comment by mcaceresb** [comment]
I have all the dependencies in pom. `mvn package` runs fine but when I try to run the file it yells that the class was not found.

**Comment by mcaceresb** [comment]
```
# stuff ...
INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.190 s
[INFO] Finished at: 2018-11-02T01:13:58-04:00
[INFO] ------------------------------------------------------------------------
java -cp target/parquetTest-0.1.0.jar com.parquetTest.app.App
Hello World!
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/arrow/memory/BufferAllocator
        at com.parquetTest.app.App.main(App.java:13)
Caused by: java.lang.ClassNotFoundException: org.apache.arrow.memory.BufferAllocator
# more backtrace ...
```

**Comment by kylebarron** [comment]
Can you share what your folder looked like at that time? Is it on git?

**Comment by mcaceresb** [comment]
Not on git. I just wanted to read and write something (literally anything) using the arrow library in Java before diving into your Stata repo. I don't have any hopes for helping in any meaningful way if I can't even manage that.

Have you managed to read/write anything using arrow? If so I'm happy to try that rather than debugging my botched attempt.

**Comment by kylebarron** [comment]
Not yet. I posted my avenues for progress above. https://github.com/mcaceresb/stata-parquet/issues/12#issuecomment-435252862

**Comment by kylebarron** [comment]
Progress!!!

![image](https://user-images.githubusercontent.com/15164633/47958210-42e58e00-df9d-11e8-84d2-a2be03b937e3.png)

That's not quite as nice as it may seem, because those rows are just printed strings from Java, so data hasn't made it to Stata yet, but it's a start!

**Comment by kylebarron** [comment]
Work is proceeding on this branch: https://github.com/kylebarron/stataParquet/tree/dev-tideworks-dataload

**Comment by kylebarron** [comment]
I just found the [Getting Started guide](https://avro.apache.org/docs/current/gettingstartedjava.html) for Avro, so I may be able to improve on the below

---

So the code I used from [someone](https://www.reddit.com/r/java/comments/8kp5av/writing_parquet_format_data_to_regular_files_ie/) [else](https://github.com/tideworks/arvo2parquet) reads Parquet data into the "Apache Avro" format in memory in Java. This is actually really helpful because it takes care of the columnar-to-row conversion for us.

I just haven't figured out how to get data out of the Avro format in a typed manner that will work in Stata.

![image](https://user-images.githubusercontent.com/15164633/47958897-9232bb00-dfab-11e8-80da-9739a7caa06a.png)

Basically where this fails is getting the data out of Avro's [`GenericData.Record`](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/generic/GenericData.Record.html). When you call `record.get()`, the return type is [`Object`](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/generic/GenericData.Record.html#get(int)), which seems to be unable to coerce to a long.

Maybe you're supposed to ["compile" a special reader](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/compiler/specific/SpecificCompiler.html) for that specific dataset with a given schema.

---

In any case, the [Java API to Stata](https://www.stata.com/java/api15/com/stata/sfi/Data.html) is nicer. From Java, you can create and drop variables, run Stata commands and get their return code, set the number of observations.

- Another helpful resource: https://layer4.fr/blog/2016/11/19/parquet-files-hadoop/

**Comment by mcaceresb** [comment]
Hooray!

Avro looks like JSON? I wonder if the nested print is just for show. The underlying structure of these thigs might be flat.... In any case, if you can loop through it you can put it in and out of Stata. Can you print, say, column j row i?

---

For sure the Java API is better. Like, way better and it is a proper API. As far as I can tell, it is similar to the mata API for Stata. All I'd really need in C or C++ is create and drop for variables and observations, but I'm not holding my breath.

In any case, it should make it easier.

**Comment by kylebarron** [comment]
> Avro looks like JSON?

I think it's record based, and not hierarchical...

> I wonder if the nested print is just for show. 

Yeah, you didn't see the code, but it was basically
```
print(record)
print(record.schema)
```
So the latter is the string representation of the schema of the record. The first line printed is the string representation of the record itself.

> Can you print, say, column j row i?

I think that's easy, but that's still the string representation of the data. I don't know how to access the _typed_ representation of the data yet.

> As far as I can tell, it is similar to the mata API for Stata. Yeah that seems to be the case.

**Comment by mcaceresb** [comment]
> I don't know how to access the typed representation of the data yet.

I see. So you can't tell the type of column j? I would almost assume that `record.schema` would have a method called `type(j)` or `column(j).type()`.

**Comment by kylebarron** [comment]
I haven't figured that part out yet:

> Basically where this fails is getting the data out of Avro's [`GenericData.Record`](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/generic/GenericData.Record.html). When you call `record.get()`, the return type is [`Object`](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/generic/GenericData.Record.html#get(int)), which seems to be unable to coerce to a long.

**Comment by mcaceresb** [comment]
Cool. Well, I still can't get a standalone example to compile (don't really know how to debug Java); keep me posted on your progress either way.

**Comment by kylebarron** [comment]
Where are you getting stuck? You can get a hello world example without maven, right?

**Comment by mcaceresb** [comment]
Whenever I try to use any parquet or arrow function I get some error. I can put it up if you really want to take a look but I don't think it will be very helpful.

Once you have a working read/write example in your repo I can try that out from Stata.

**Comment by kylebarron** [comment]
I mean I have a working "print string data in Stata" that works that you could look at if you wanted to.

**Comment by mcaceresb** [comment]
I thought you hadn't gotten to looping through the data?

**Comment by kylebarron** [comment]
It loops through each row and prints it. It doesn't yet loop through each cell of the row while printing to the screen, but that's trivial. The issue is that when looping through each cell, I see it as a general object and not as a specific type.

**Comment by mcaceresb** [comment]
Ok; I'll give it a shot later tonight.

**Comment by mcaceresb** [comment]
Well, I'm not really sure what to do in the repo. `mvn` yells at me about `com.stata.sfi` but I don't know where to copy `sfi-api.jar` to make that work. I think I might to take some time to figure out Java before I can make any meaningful progress.

**Comment by kylebarron** [comment]
https://github.com/kylebarron/stataParquet/blob/master/CONTRIBUTING.md

**Comment by mcaceresb** [comment]
Cool. Not sure how to compile. I gather I'm supposed to do something like 

```
javac -cp target/stataParquet-0.1.0.jar src/main/java/com/kylebarron/stataParquet/DataLoad.java
```

or 

```
javac -cp target/stataParquet-0.1.0.jar com.kylebarron.stataParquet.DataLoad
```

but both fail (and some variations thereof).

**Comment by kylebarron** [comment]
1. Run `mvn package`. That creates `target/stataParquet-0.1.0-jar-with-dependencies.jar`.
2. Symlink that to wherever your `PERSONAL` directory is.
3. Run
```
javacall com.kylebarron.stataParquet.DataLoad sayhello, jar(name of symlink.jar)
```

The `.jar` is already compiled code.

**Comment by mcaceresb** [comment]
It worked!

**Comment by kylebarron** [comment]
What did you have to change?

**Comment by mcaceresb** [comment]
Restart stata.

**Comment by kylebarron** [comment]
If you're not using Stata 15 you have to always restart Stata apparently. With Stata 15 it seems to work for me without restarting.

**Comment by kylebarron** [comment]
If you go to this commit (https://github.com/kylebarron/stataParquet/commit/e6b6985d94be31e8d4d2e930154604c8b55cd921) then you can print arbitrary Parquet data to the screen.

In the later two commits on that branch, I depend on a specific Parquet file.

**Comment by kylebarron** [comment]
Did you end up testing this at all?

**Comment by mcaceresb** [comment]
The call worked from Stata, I didn't get to adding or removing stuff.

**Comment by kylebarron** [comment]
oh. my. god. Such a stupid mistake... 

I always write strings with single quotes by default because I think they look cleaner than double strings. Well, with Java, (and maybe C/C++ too?) `'x'` is of type `char` and `"x"` is of type `string`. So `record.get('a')` was crashing because I was providing `char` as input and not `string`. I'm surprised that the compiler didn't stop that though? I thought it was supposed to catch these sorts of things...

**Comment by kylebarron** [comment]
Success!
![image](https://user-images.githubusercontent.com/15164633/48036568-f766e780-e136-11e8-91cf-7b1773f7967b.png)

**Comment by kylebarron** [comment]
Pretty much, my issue now is that I'm having difficulty finding the number of rows in the dataset. The reader I'm using automatically converts to rows. So each row has a schema for the row only.

**Comment by kylebarron** [comment]
Yay:
![image](https://user-images.githubusercontent.com/15164633/48082211-f4640980-e1bf-11e8-8373-53f0489c27d4.png)
![image](https://user-images.githubusercontent.com/15164633/48082218-f928bd80-e1bf-11e8-80bb-8a91c15e8082.png)

**Comment by mcaceresb** [comment]
Cool beans! Does it do strings or is that a lot harder?

**Comment by kylebarron** [comment]
It takes .41 seconds to read in 1million obs x 4 variables, all long, whereas that's like 0.02 seconds in Stata.

Strings shouldn't be a lot harder. I just haven't figured out how to compare the types in the schema to fixed types to know what to make each variable as.

**Comment by mcaceresb** [comment]
You ought to benchmark just the Java read times. I imagine most of that is overhead.

**Comment by kylebarron** [comment]
I got strings to work as well. I just have to figure out the schema types

![image](https://user-images.githubusercontent.com/15164633/48083235-a997c100-e1c2-11e8-8771-b6c34b2cca0a.png)

**Comment by kylebarron** [comment]
(That string is set to width 1 in Stata, then Stata automatically widens it as I add wider values)

**Comment by mcaceresb** [comment]
The schema will allow you to allocate it as str#, right? You could also scan the first # values for the longest string and then import. Stata will re-size if necessary and it might obviate the need to loop through all the columns to find the max. (Of course, if the schema has that info already it would be ideal.)

**Comment by kylebarron** [comment]
Unless it's a fixed byte array, it won't have the string length. And since those are rare, I'm not going to put effort into that now. If Stata can resize the columns and not take too big of a performance penalty, that's ideal.

**Comment by mcaceresb** [comment]
If you have a string in Java, you can't do "myString.Length()"?

**Comment by kylebarron** [comment]
Yes but that's assuming that I've loaded the first row of data before creating columns.

**Comment by mcaceresb** [comment]
But you can do that in Java, no?

**Comment by kylebarron** [comment]
I have a working program that reads arbitrary files into Stata now...

**Comment by mcaceresb** [comment]
Very very cool! What's the next step? Write? Or are you going to benchmark it first?

**Comment by kylebarron** [comment]
Were you able to test it?

I feel that stability in reading is most important. Also this architecture might still not be ideal. For example, I'm not sure if this architecture allows for fast reads of selected columns

**Comment by kylebarron** [comment]
The working Stata implementation, in [this file](https://github.com/kylebarron/stataParquet/blob/master/src/main/java/com/kylebarron/stataParquet/ParquetStataReader.java), uses a completely different library as the implementation in [Main.java](https://github.com/kylebarron/stataParquet/blob/master/src/main/java/com/kylebarron/stataParquet/Main.java), which I think still reads a column of data at a time. The latter successfully prints data to the Stata console I think.

**Comment by mcaceresb** [comment]
I can't get it to work, btw. It's in master now, right? I get this

```
. javacall com.kylebarron.stataParquet.ParquetStataReader read,  jar(stataParquetShaded.jar) args("sample.parquet")
java.lang.ClassNotFoundException: com.kylebarron.stataParquet.ParquetStataReader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.stata.Javacall.load(Javacall.java:119)
        at com.stata.Javacall.load(Javacall.java:90)
r(5100);
```

I ran

```
git clone https://github.com/kylebarron/stataParquet
cd stataParquet
ln -sf ~/.local/stata15/utilities/jar/sfi-api.jar .
mvn install:install-file -DgroupId=com.stata -DartifactId=sfi -Dversion=15 -Dpackaging=jar -Dfile=sfi-api.jar
mvn package
ln -sf ${PWD}/target/stataParquet-0.1.0-jar-with-dependencies.jar ~/ado/personal/
```

**Comment by mcaceresb** [comment]
I guess the `stataParquetShaded.jar` should really be `stataParquet-0.1.0-jar-with-dependencies.jar`; wasn't really sure why that had changed but I guess there was some renaming that hasn't made it to master?

**Comment by kylebarron** [comment]
Sorry, with recent changes you actually have to symlink `target/stataParquet-0.1.0.jar`, though that does still contain all dependencies (as you can tell from the size).

**Comment by kylebarron** [comment]
It's because I had to use an extra plugin to get the Hadoop dependency (not all of hadoop) to work, and so for some reason the jar that works is stataParquet.jar.

**Comment by kylebarron** [comment]
Does this mean you got it to work?

**Comment by mcaceresb** [comment]
You still haven't implemented types or NaNs, right? Reading `float` and missing values fails atm, but that is expected no?

```
local stataParquet com.kylebarron.stataParquet.ParquetStataReader 
local jarParquet stataParquet-0.1.0-jar-with-dependencies.jar
clear
set obs 10000000
gen double x = rnormal()
gen y = "strings!"
save test.dta, replace
parquet save test.parquet, replace
set rmsg on
```

Very cool!
```
. javacall `stataParquet' read,  jar(`jarParquet`) args("test.parquet")
r; t=8.19 16:22:19

. !printf 'import pandas as pd\npd.read_parquet("test.parquet")' | python

r; t=1.51 16:22:20
```

**Comment by mcaceresb** [comment]
Interesting the C++ version is faster than the pandas import; I assume it is due to the way it checks strings (i.e. not entirely thoroughly).

```
. parquet use test.parquet, clear
Scanned column types (0.00 sec).
Read data into Arrow table (0.39 sec).
Copied table into Stata (0.48 sec).
        File:    test.parquet
        Columns: 2
        Rows:    10000000
r; t=1.13 16:22:57
```

**Comment by mcaceresb** [comment]
I thought it might be `pyarrow` but `fastparquet` is slower on my system

```stata
. !printf 'import pandas as pd\npd.read_parquet("test.parquet", engine="fastparquet")' | python

r; t=2.50 16:26:58
```

**Comment by kylebarron** [comment]
> You still haven't implemented types or NaNs, right? Reading `float` and missing values fails atm, but that is expected no?

I was thinking that `float` should work. I was never able to figure out how to compare types using the `parquet-hadoop` library, so I'm looking at the Avro types after conversion. The schema is kinda weird though... It's like `["null", "int"]`, which I think means the column is integer but can have null values... so I have to often check if one of the types in the array is int, float, etc.

**Comment by mcaceresb** [comment]
I think this is also the case in Java (the API, I mean), but the way Stata does it is that everything past the largest value for a data type is a missing value. So a NaN or NULL would just be a super large double in Stata (this also holds for smaller types, so a 200 is missing for a byte).

**Comment by kylebarron** [comment]
I'm going to leave it be for now. I think that if I want to import Parquet files with high performance, I need to use the `parquet-hadoop` library.

**Comment by kylebarron** [comment]
Closing, since I don't think it's worth reinventing the wheel at this point.
