### ISSUE TITLE
Support reading "Parquet Datasets"

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/stata-parquet#14]
Parquet files written by Spark or with `fastparquet` with the option `file_scheme=hive` are written into folders with the name `filename.parquet/`, with multiple files inside, one for each row group, to help with parallel reads. This isn't currently supported here.

```
> ll med1999.parquet
total 16M
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00000-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00001-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00002-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00003-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00004-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00005-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00006-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00007-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00008-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00009-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00010-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00011-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00012-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00013-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00014-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 1.1M Nov  3 11:17 part-00015-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929 940K Nov  3 11:17 part-00016-28fcf1da-b8f8-49ca-ab2f-c5bd65e2d65c-c000.snappy.parquet
-rw-r--r-- 1 barronk-dua51929 dua51929    0 Nov  3 11:17 _SUCCESS
```

![image](https://user-images.githubusercontent.com/15164633/48212951-b5ae8a80-e34a-11e8-93ea-708360f9d896.png)

You can create a similar dataset with `fastparquet` with:
```py
import pandas as pd
import numpy as np
import fastparquet as fp
df = pd.DataFrame(np.random.randint(0,100,size=(4, 4)), columns=list('ABCD'))
fp.write('test.parquet', df, row_group_offsets=2, file_scheme='hive')
```

**Comment by mcaceresb** [comment]
I suppose I could loop through the files, having each file read in parallel? I don't think arrow supports treating the directory as the file somehow. One problem with the python example is that each individual file has 1 group and 4 rows in the metadata but in effect only 2 rows of data.

What happens if you read just one of the MedPAR files?

**Comment by mcaceresb** [comment]
I suppose I could wrap the call in a multi-threaded loop with one thread per file... But, I mean, I really don't think the C++ API supports treating that folder as a single file.

Can you import just one of them?

**Comment by kylebarron** [comment]
You might want to look at Pyarrow's implementation of [`ParquetDataset`](https://github.com/apache/arrow/blob/dccec7af96dec2b09359938fc39037eaaef96f95/python/pyarrow/parquet.py#L802). It get's a [list of pieces](https://github.com/apache/arrow/blob/dccec7af96dec2b09359938fc39037eaaef96f95/python/pyarrow/parquet.py#L856-L860), and then simply [loops over the pieces when reading](https://github.com/apache/arrow/blob/dccec7af96dec2b09359938fc39037eaaef96f95/python/pyarrow/parquet.py#L938-L944), calling each's `.read()` method.

**Comment by mcaceresb** [comment]
I'm thinking this:

1. Accept a directory or a wild card (glob)
2. All `.parquet` files in dir or matching the glob must have the same variables.
3. In the case of python, all files must have the same number of rows.
4. The sum of rows read must equal the total number of rows across files.

Problem: How to check the number of rows per group for parallel reads? Sequential reads won't be an issue if this is just a wrapper for reading a list of files.

**Comment by kylebarron** [comment]
As expected, you can't read each piece individually. 
![image](https://user-images.githubusercontent.com/15164633/48233284-a0ede900-e382-11e8-971a-2612ea0fae73.png)

**Comment by mcaceresb** [comment]
Can you give me sample code to generate something like that? It can read the python files individually just fine.

**Comment by mcaceresb** [comment]
Actually, if you update to the latest version in the repo it reads them just fine. There's a ton of missing values, I'm assuming because the rest of the data is in the other files.

```
. pwd
/disk/agebulk3/medicare.work/doyle-dua51929/barronk-dua51929/raw/pq_from_spark/01pct/med/med2012.parquet

. parquet use part-00000-863c36b3-bd34-4eb3-9149-3d7c5243e080-c000.snappy.parquet, clear
Scanned column types (0.03 sec).
        File:    part-00000-863c36b3-bd34-4eb3-9149-3d7c5243e080-c000.snappy.parquet
        Groups:  1
        Columns: 365
        Rows:    5408
Warning: 580685 NaN values in string variables coerced to blanks ('').
Read data from disk (0.05 sec).
```

**Comment by kylebarron** [comment]
Interesting. I suppose it sees metadata that calls for 600,000 obs, but only fills in 5500

**Comment by mcaceresb** [comment]
Are there supposed to be 600k obs? I only get to 167k:

```
tempfile bene
local N = 0
local files: dir "." files "*.parquet"
clear
gen bene_id = ""
foreach f of local files {
    preserve
    qui parquet use bene_id using `f', clear
    assert !mi(bene_id)
    disp _N, "`f'"
    local N = `N' + `=_N'
    qui save `bene', replace
    restore
    append using `bene'
}
disp %21.0gc `N', %21.0gc _N
```

**Comment by kylebarron** [comment]
You're correct. There's 168,000 obs in the Stata file:
![image](https://user-images.githubusercontent.com/15164633/48234131-4bb3d680-e386-11e8-91e3-4076b803a36a.png)

**Comment by mcaceresb** [comment]
Oh, cool. So it can already read parquet folders made by Spark, just not in parallel.

The issue remains with those made in pyarrow/fastparquet, since the # of obs says the total, not how many in each individual file.

**Comment by kylebarron** [comment]
For the record, when reading the Parquet dataset into Pandas, I also get 167905 obs.

**Comment by kylebarron** [comment]
I was just guessing the 600,000 obs from the statement
```
Warning: 580685 NaN values in string variables coerced to blanks ('')
```

**Comment by mcaceresb** [comment]
No, that is the aggregate number of missing string values for the entire dataset. I guess it's a confusing statement.

**Comment by kylebarron** [comment]
I have no idea what kind of gains would be possible by trying to read them in in parallel. Sounds hard, and you might be limited by Stata no matter what.

**Comment by kylebarron** [comment]
It makes sense on the second read.

**Comment by mcaceresb** [comment]
I don't think I can for the python export, but I def think I can set it up for the snappy export bc the # of rows in the file's metadata is the number of rows in the file. I just don't know if the speed gains will be there.

Parallel loops for Unix in C is not that hard with OpenMP, so maybe it will be comparably easy in C++; I just don't use it more often bc I can't get it to work on Windows or OSX (or some versions of Linux for that matter, but it works in the server).

**Comment by mcaceresb** [comment]
There is some support for this in `develop`.

```
. pwd 
/disk/agebulk3/medicare.work/doyle-dua51929/barronk-dua51929/raw/pq_from_spark/100pct/med

. set rmsg on
r; t=0.00 21:26:31

.  parquet use bene_id using med2012.parquet, clear
Scanned column types (0.62 sec).
         Dir:     med2012.parquet
         Groups:  121
         Columns: 1
         Rows:    16803497

Read data from disk (1.40 sec).
r; t=3.50 21:26:39
```

**Comment by kylebarron** [comment]
Very cool
