### ISSUE TITLE
Read by row group

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/stata-parquet#17]
Might be helpful to have an option to read Parquet files by row group. This is probably more efficient than the extra parsing required for `in()`, and would also give evenly spaced amounts of data. Would also necessitate a `parquet desc` which prints to `r()` the number of row groups in the file. Then you could loop:

```stata
parquet desc using file.parquet
foreach i of numlist 1/r(n_row_groups) {
	parquet use file.parquet, rg(`i')
	// do something with data chunk 
}

**Comment by mcaceresb** [comment]
Yes. I don't think it's any more efficient but it's def a good idea. What is the behavior for reading group 9 if it doesn't exist? Error or soft warning?

**Comment by mcaceresb** [comment]
Actually, it might be more efficient for the high-level reader. For the low-level reader I iterate over row groups anyway, but in the high level reader I read the table and then iterate. If there are many row groups it could certainly be way faster to read only one.

**Comment by mcaceresb** [comment]
Other Q: Is rg(1) row group 1 or row group 0? (i.e. is the user-defined rg 0-indexed? Internally it is, but do I subtract 1?)

**Comment by kylebarron** [comment]
> Yes. I don't think it's any more efficient but it's def a good idea. What is the behavior for reading group 9 if it doesn't exist? Error or soft warning?

I don't understand the intricacies of how you parse lines inside a row group, since I've never seen that in another Parquet reader. Generally reading a group number that doesn't exist would raise an error.

> Other Q: Is rg(1) row group 1 or row group 0? (i.e. is the user-defined rg 0-indexed? Internally it is, but do I subtract 1?)

I think in the context of Stata it would be easiest to start numbering at 1. So if internally row groups are numbered starting from 0, start user numbering at 1 and subtract 1.

**Comment by mcaceresb** [comment]
For reading hive files, is a row group relative to each file or relative to the entire set? The entire set, right?

**Comment by kylebarron** [comment]
For parquet datasets, each individual file is a row group

**Comment by mcaceresb** [comment]
But each individual file can have row groups as well.Interesting.

**Comment by mcaceresb** [comment]
Actually, that's much easier to implement since I can just discard the listed datasets not in the row groups requested.
